### PR TITLE
Send2UE - Use Collections as Folders Animation & Groom Support

### PR DESCRIPTION
**Pull request by JoshQuake**
Implementing @SaltyPandaCedric / @eXifreXi contribution adding Animation support to Use Collections as Folders

### CODE REVIEW

**Comment by JoshQuake** [comment]
Hmmm I get that error as well even when this extension isnt enabled. They also _do_ exist. This is after running with use collections as folders unchecked, bypassing the extensions entirely.
image

**Comment by JoshQuake** [comment]
It happens with the apps open and manually testing the mannequins.blend. I get the error, but the binding is there and when you open it the target skeleton is correctly set.

**Comment by JoshQuake** [comment]
errors out at 451 when creating the groom asset. However it then sets the missing target skel right after, negating the error. https://github.com/poly-hammer/BlenderTools/blob/e44b3a4ae489d2e78dd9cada4d587a325a253798/src/addons/send2ue/dependencies/unreal.py#L451

**Comment by jack-yao91** [comment]
Hmm weird, I wonder if there is an alternative API call? Or maybe its just a bug in the python API that hasnt been reported.

**Comment by jack-yao91** [comment]
What about adding a breakpoint at 410? Might be something to do with the asset_tools API. Ill see if I can dig into this too

**Comment by JoshQuake** [comment]
feel free to work in the branch. I'm done working on it for the day and will be starting on #28 tonight after a break

**Comment by jack-yao91** [comment]
Hmm ok unreal 5.4 freezes up for me everytime when 
`bpy.context.scene.send2ue.extensions.create_post_import_assets_for_groom.blueprint_with_groom = True`

I just opened the mannequins.blend from the tests
image

Is it not freezing for you? Seems like only 5.3 works for me. 5.4 locks up and I have to kill unreal from task manager

**Comment by JoshQuake** [comment]
I've been using 5.4 without freezes but I dont think that extension has been enabled in my testing

**Comment by JoshQuake** [comment]
I was wrong that extension is active since it is by default

**Pull request merged**
