### PR TITLE
[UE2Rigify] Added Blender 4 Compatibility

### PR DESCRIPTION
**Pull request by JoshQuake**
- Added support for Blender 4+ while maintaining Blender 3.6 compatibility.
- Added @gzmuszynski's UE mannequin rigs.

### CODE REVIEW

**Comment by JoshQuake** [comment]
Hmm action didnt trigger

**Comment by jack-yao91** [comment]
Ah yes I have to the workflow setup to run on push. We could change it to run on PR if the branch was a PR from this repo. Just for security reasons, it would be too easy for someone to PR changes to `run_tests.py` and execute arbitrary python code on our runners.

I created a dev branch, so maybe we can intake PRs to the dev branch and then the CI will run then we can squash and merge to main when tests are passing.

**Review by jack-yao91 — APPROVED** [review]

**Comment by JoshQuake** [comment]
I like the dev branch idea that would be great!

**Comment by jack-yao91** [comment]
Actually so I did a little digging and looks like I can set the repo settings to not run PRs on forks from unknown members unless approved first. To there would just be a manual step of approving the workflow run, which will let us look at the code in the PR first, which should achieve the same goal as with what I was proposing with the dev branch. So Ill give that I shot.

**Pull request merged**
